# Generated by Django 2.1.2 on 2018-10-25 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='board',
            new_name='dude',
        ),
    ]
