# Generated by Django 2.1.2 on 2018-10-25 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_auto_20181025_1012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='dude',
            new_name='board',
        ),
    ]
