# Generated by Django 2.1.2 on 2018-10-26 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_auto_20181025_1040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='topic',
            new_name='topi',
        ),
    ]
