# Generated by Django 2.1.2 on 2018-10-26 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0007_auto_20181026_1631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='topi',
            new_name='topic',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='bo',
            new_name='board',
        ),
    ]
